# Generated by Django 3.0.3 on 2020-02-29 11:56

from django.db import migrations, models
import django.db.models.deletion
import hotels.utility


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingManager',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('cust_full_name', models.TextField()),
                ('cust_mail_id', models.EmailField(blank=True, max_length=254)),
                ('cust_phone_number', models.TextField()),
                ('cust_pan_number', models.TextField(blank=True)),
                ('total_nights', models.IntegerField()),
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HotelManager',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('country', models.TextField()),
                ('zip_code', models.TextField()),
                ('phone_number', models.TextField()),
                ('email_address', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to=hotels.utility.hotel_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='RoomTypeManager',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
                ('hotel_id_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.HotelManager')),
            ],
        ),
        migrations.CreateModel(
            name='RoomManager',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_name', models.TextField()),
                ('image', models.ImageField(upload_to=hotels.utility.room_directory_path)),
                ('room_type_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.RoomTypeManager')),
            ],
        ),
    ]
