# Generated by Django 3.0.3 on 2020-03-01 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_bookingmanager_receptionist_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmanager',
            name='room_key',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotels.RoomManager'),
            preserve_default=False,
        ),
    ]
