# Generated by Django 3.0.3 on 2020-03-01 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_bookingmanager_room_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmanager',
            name='cust_full_name',
            field=models.TextField(verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='bookingmanager',
            name='cust_mail_id',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Customer Email'),
        ),
        migrations.AlterField(
            model_name='bookingmanager',
            name='cust_pan_number',
            field=models.TextField(blank=True, verbose_name='Customer PAN'),
        ),
        migrations.AlterField(
            model_name='bookingmanager',
            name='cust_phone_number',
            field=models.TextField(verbose_name='Customer Phone'),
        ),
        migrations.AlterField(
            model_name='bookingmanager',
            name='room_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.RoomManager', verbose_name='Room'),
        ),
    ]
